admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

app_default:
    resource: AppBundle\Controller\DefaultController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"