security:

    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/autentica, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/sync, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY  }
